### ISSUE TITLE
Singularize() throws `IndexOutOfRangeException`

### ISSUE THREAD

**Issue by terrajobst** [Humanizr/Humanizer#1219]
This code results in an exception:

```C#
"S".Singularize();
```
Exception:

```text
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Humanizer.Inflections.Vocabulary.MatchUpperCase(String word, String replacement) in /_/src/Humanizer/Inflections/Vocabulary.cs:line 158
   at Humanizer.Inflections.Vocabulary.ApplyRules(IList`1 rules, String word, Boolean skipFirstRule) in /_/src/Humanizer/Inflections/Vocabulary.cs:line 148
   at Humanizer.Inflections.Vocabulary.Singularize(String word, Boolean inputIsKnownToBePlural, Boolean skipSimpleWords) in /_/src/Humanizer/Inflections/Vocabulary.cs:line 114
```

**Comment by aloisdg** [comment]
I guess that the problem come from here:

https://github.com/Humanizr/Humanizer/blob/637413950a4e834d4e626d53b3a2db62fc4772c8/src/Humanizer/Inflections/Vocabulary.cs#L174

**Comment by neilboyd** [comment]
Fixed in #1154

**Comment by terrajobst** [comment]
The bug is still present. Please not that this isn't the lower-case letter 's' but the upper case letter 'S'.

**Comment by SimonCropp** [comment]
@terrajobst if u have time, you could try the beta https://www.nuget.org/packages/Humanizer/3.0.0-beta.13

**Comment by terrajobst** [comment]
Just did, seems to have fixed the issue.
