### ISSUE TITLE
Titlize removes decimal point

### ISSUE THREAD

**Issue by TQ-Benji** [Humanizr/Humanizer#1261]
Odd behavior it's removing the decimal point

Example
"thisIs3.5mmLong".Titleize() => "This Is 3 5mm Long"

Expect it to return "This Is 3.5mm Long"

NET 7
Humanizer version 2.14.1

**Comment by LOne2three** [comment]
I have fixed the issue on my fork and will send a pull request

**Comment by Exilon24** [comment]
I can't find this method. Where is it located?

**Comment by TQ-Benji** [comment]
Hi, It's this method 

https://github.com/Humanizr/Humanizer/blob/1bdd7a1bad03fd001d04fc0e252d279b4e785818/src/Humanizer/InflectorExtensions.cs#L62

**Comment by LOne2three** [comment]
I have fixed this issue but awaiting pull request approval

**Comment by clairernovotny** [comment]
Thanks for the report. I re-tested this against current `main` (`b7b396b2`), and the original result still reproduces:

```csharp
"thisIs3.5mmLong".Titleize() // "This Is 3 5mm Long"
```

This is a consequence of `Titleize()`'s documented composition: it first calls `Humanize()` to turn a programming identifier into words, then applies title casing. The identifier-humanization parser intentionally extracts recognized word parts and discards unsupported punctuation; the existing tests cover that behavior with inputs such as `"ContainsSpecial?)@Characters"` becoming `"Contains special characters"`. Treating only digit-dot-digit as preserved punctuation would therefore change the established `Humanize()` contract, not make a narrow `Titleize()` correction.

For text whose punctuation and spacing should already be preserved, use the casing layer directly:

```csharp
input.Transform(To.TitleCase)
// or CultureInfo.CurrentCulture.TextInfo.ToTitleCase(input)
```

Those APIs preserve the decimal point, but deliberately do not infer camel-case word boundaries. When the input is a domain-specific identifier that needs both behaviors, split its supported boundaries first (or put that rule in an `IStringTransformer`) and then compose with `To.TitleCase`. For this example, the following produces the requested value without changing Humanizer's identifier grammar:

```csharp
Regex.Replace(input, @"(?<=[a-z])(?=[A-Z0-9])", " ")
    .Transform(To.TitleCase);
// "This Is 3.5mm Long"
```

Because the punctuation-preserving path is supported through `TextInfo`/`To.TitleCase`, and identifier-specific preservation rules can be expressed with a custom transformer, there is no narrow backward-compatible library fix to make here. I'm closing this as not planned.
