### ISSUE TITLE
MakePRI warning 0xdef01051 while compiling Windows 8.1 Store app

### ISSUE THREAD

**Issue by pedropombeiro** [Humanizr/Humanizer#317]
After I added Humanizer to the solution (an English only project), I started getting the following warnings during the build:

```
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/DateHumanize_MultipleSecondsAgo_Dual'. The application may throw an exception for certain user configurations when retrieving the resources.
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/DateHumanize_MultipleSecondsFromNow_Plural'. The application may throw an exception for certain user configurations when retrieving the resources.
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/DateHumanize_MultipleHoursFromNow_Dual'. The application may throw an exception for certain user configurations when retrieving the resources.
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/TimeSpanHumanize_MultipleDays_Dual'. The application may throw an exception for certain user configurations when retrieving the resources.
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/TimeSpanHumanize_MultipleHours_Plural'. The application may throw an exception for certain user configurations when retrieving the resources.
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/DateHumanize_MultipleYearsFromNow_Dual'. The application may throw an exception for certain user configurations when retrieving the resources.
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/TimeSpanHumanize_MultipleMinutes_Plural'. The application may throw an exception for certain user configurations when retrieving the resources.
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/TimeSpanHumanize_MultipleMinutes_Dual'. The application may throw an exception for certain user configurations when retrieving the resources.
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/TimeSpanHumanize_MultipleSeconds_Plural'. The application may throw an exception for certain user configurations when retrieving the resources.
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/DateHumanize_MultipleMinutesFromNow_Plural'. The application may throw an exception for certain user configurations when retrieving the resources.
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/TimeSpanHumanize_MultipleMilliseconds_Dual'. The application may throw an exception for certain user configurations when retrieving the resources.
6>MakePRI : warning 0xdef01051: No default or neutral resource given for 'Humanizer.Properties.Resources/TimeSpanHumanize_MultipleDays_Plural'. The application may throw an exception for certain user configurations when retrieving the resources.
```

When I search the web for the warning code, I came across this: http://social.msdn.microsoft.com/Forums/windowsapps/en-US/2554a1c6-f1b8-45b1-a690-881d835407d0/how-to-solve-makepri-warning-0xdef01051-no-default-or-neutral-resource-given-for?forum=toolsforwinapps

Is this a known issue?

Thanks.

**Comment by MehdiK** [comment]
I think this is now fixed through #374 & it's been released to NuGet. Would you please be able to verify if the warnings have gone away.

**Comment by PombeirP** [comment]
@MehdiK They are indeed gone!

I still have a minor one though, not sure if you've seen it before:
`plex-win8\packages\Humanizer.1.33.0\lib\portable-win+net40+sl50+wp8+wpa81\Humanizer.dll : error CS1684: Warning as Error: Reference to type 'System.IConvertible' claims it is defined in 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5.1\mscorlib.dll', but it could not be found`
