### ISSUE TITLE
A Visual Studio Mac update broke my Xamarin build with a Humanizer error

### ISSUE THREAD

**Issue by buzzware** [Humanizr/Humanizer#621]
This issue appeared when I updated Visual Studio for Mac. Going back in git history, old code fails the same way, so something has changed in the build process where it no longer accepts Humanizer like it did before.

It sounds a bit like "the real issue is that the wrong TargetFrameworkAttribute is on Humanizer for some reason" https://github.com/Humanizr/Humanizer/issues/573 but it is beyond my understanding of the whole .Net profile mess.

The upshot is that I can no longer build my project with the current IDE. I guess I'll have to downgrade the IDE.

"/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3274: The primary reference "Humanizer" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111". (MSB3274) (FreeXam.XPlatform.Lib)"

Then in my code, on "using Humanizer" I get :
"/Users/gary/repos/freewheeler/FreeXam/FreeXam.XPlatform.Lib/Utils/FreeUtils.cs(7,7): Error CS0246: The type or namespace name `Humanizer' could not be found. Are you missing an assembly reference? (CS0246) (FreeXam.XPlatform.Lib)"

**Comment by buzzware** [comment]
The latest Visual Studio for Mac updated to Stable channel has this issue, while the latest Xamarin Studio for Mac does not. Here are their about info contents :

VS for Mac which fails :

=== Visual Studio for Mac Preview ===

Version Preview 4 (7.0 build 1566)
Installation UUID: 6d293865-d662-4140-bf98-1d7bca839a17
Runtime:
	Mono 4.8.0 (mono-4.8.0-branch/f5fbc32) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 408000344

=== NuGet ===

Version: 4.0.0.2275

=== Xamarin.Profiler ===

Version: 1.0.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 7.0.2.37 (Visual Studio Enterprise)
Android SDK: /Users/gary/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.1   (API level 16)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)

SDK Tools Version: 25.2.2
SDK Platform Tools Version: 25
SDK Build Tools Version: 24

Java SDK: /usr
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 8.0 (11246)
Build 8A218a

=== Xamarin.Mac ===

Version: 2.10.0.113 (Visual Studio Enterprise)

=== Xamarin Inspector ===

Version: 1.1.2.0
Hash: cdc01b9
Branch: 1.1-release
Build date: Wed, 22 Feb 2017 23:24:11 GMT

=== Xamarin.iOS ===

Found unsupported Xamarin.iOS, version 10.2.1.5.
You need Xamarin.iOS 10.4 or above.

=== Build Information ===

Release ID: 700001566
Git revision: 2f11ef3c8909b95abcccc1b635c874f8eabf6ba0
Build date: 2017-03-06 18:12:59-05
Xamarin addins: 2bfd615b170b882de02930d3bceaf014c08b5540
Build lane: monodevelop-lion-vs-mac-preview4

=== Operating System ===

Mac OS X 10.11.6
Darwin Garys-MBP.gateway 15.6.0 Darwin Kernel Version 15.6.0
    Wed Nov  2 20:30:56 PDT 2016
    root:xnu-3248.60.11.1.2~2/RELEASE_X86_64 x86_64


--------------------------------------------------------------------------------------------
Updated XSC which builds OK :

Xamarin Studio Community
Version 6.2 (build 1821)
Installation UUID: 972e9eda-ec73-464e-a091-f2ea7102a1dd
Runtime:
	Mono 4.8.0 (mono-4.8.0-branch/e4a3cf3) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 408000495

NuGet
Version: 3.5.0.0

Xamarin.Profiler
Version: 1.0.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 8.0 (11246)
Build 8A218a

Xamarin.Mac
Version: 3.0.0.393 (Xamarin Studio Community)

Xamarin.Android
Version: 7.1.0.41 (Xamarin Studio Community)
Android SDK: /Users/gary/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.1   (API level 16)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)

SDK Tools Version: 25.2.2
SDK Platform Tools Version: 25
SDK Build Tools Version: 24

Java SDK: /usr
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Android Player
Version: 0.6.5
Location: /Applications/Xamarin Android Player.app

Xamarin Inspector
Version: 1.1.2.0
Hash: cdc01b9
Branch: 1.1-release
Build date: Wed, 22 Feb 2017 23:24:11 GMT

Xamarin.iOS
Version: 10.4.0.123 (Xamarin Studio Community)
Hash: 35d1ccd
Branch: cycle9
Build date: 2017-02-16 17:40:00-0500

Build Information
Release ID: 602001821
Git revision: d41b6e51f3fa46a1943f2e31a778d28a7c73d069
Build date: 2017-02-17 15:18:19-05
Xamarin addins: 1363a8d943bab7700c93a97474060b6734aa7f94
Build lane: monodevelop-lion-cycle9

Operating System
Mac OS X 10.11.6
Darwin Garys-MBP.gateway 15.6.0 Darwin Kernel Version 15.6.0
    Wed Nov  2 20:30:56 PDT 2016
    root:xnu-3248.60.11.1.2~2/RELEASE_X86_64 x86_64

Enabled user installed addins
Gorilla Player 0.9.1.2

**Comment by onovotny** [comment]
This looks like a regression introduced with the latest VSfM. It's one that was originally in VS 2015 Update 3 and was fixed in a micro-update afterwards. I've pinged the VSfM team to let them know. The latest version from the CI feed should work though as it was built a different way.

**Comment by buzzware** [comment]
Thanks for your reply.

I added https://www.myget.org/F/humanizer/api/v3/index.json as a source and upgraded Humanizer.Core to 2.2.0-beta.41, but the same problem persists.

**Comment by radical** [comment]
@buzzware Your VSMac info says that it was using an older version of mono. And then you updated it, and tried XS. Could you please try VSMac again with the updated mono and see if it also fails?

**Comment by mfegerlmedovis** [comment]
@radical still fails with current builds.

**Comment by mfegerlmedovis** [comment]
another note: it works just fine with Humanizer 2.0.1 - but not with 2.1.0

**Comment by buzzware** [comment]
Mobile Center has this issue, VSTS does not

**Comment by onovotny** [comment]
Closing this issue out as it's seems stale. Please reopen if there's still a current issue.
