### ISSUE TITLE
Precision strategy for timestamps and unexpected off-by-one error

### ISSUE THREAD

**Issue by tompazourek** [Humanizr/Humanizer#805]
```csharp
Configurator.DateTimeOffsetHumanizeStrategy = new PrecisionDateTimeOffsetHumanizeStrategy();

var inputTime1 = new DateTimeOffset(2019, 01, 27, 0, 0, 0, TimeSpan.Zero);
var inputTime2 = new DateTimeOffset(2019, 01, 28, 0, 0, 0, TimeSpan.Zero);
var inputTime3 = new DateTimeOffset(2019, 01, 29, 0, 0, 0, TimeSpan.Zero);

var baseTime   = new DateTimeOffset(2019, 03, 29, 0, 0, 0, TimeSpan.Zero);

inputTime1.Humanize(baseTime); // 2019-01-27 => 2 months ago
inputTime2.Humanize(baseTime); // 2019-01-28 => one month ago
inputTime3.Humanize(baseTime); // 2019-01-29 => 2 months ago
```

The `inputTime2` in the test case above is expected to be `2 months ago` the same as the day before and day after.

I tried to find the error in the code, but I didn't really understand how the precision strategy algorithm works. 

The same error should be happening for `DateTime`, I don't think it's related to `DateTimeOffset`.

**Comment by AKTheKnight** [comment]
I wonder if it is possibly related to the issues in #651 too.

I'm working on #800 to fix it, I'll test with these values and see if the values change.

**Comment by AKTheKnight** [comment]
Done some looking into it, here's the cause (Not sure how to fix it or what to do about it, just writing all this to make sure I understand it and see if it can help lead to a solution)

The part we are interested in starts in the DateTimeHumanizeAlgorithms#PrecisionHumanize method. For reference the value of days in this method with our tests will be 61, 60, and 59.

All the values calculate for months for these tests are done in the below lines: https://github.com/Humanizr/Humanizer/blob/81c6dbe79a629d30b7527b78ba5df990ef7a0935/src/Humanizer/DateTimeHumanizeStrategy/DateTimeHumanizeAlgorithms.cs#L51-L56

Here's the values of variables as we proceed through the if statement:

Test | days | factor | maxMonths | months
------|------|--------|-----------|--------
1    | 61   | 2      | 2         | 1      
2    | 60   | 2      | 2         | 1      
3    | 59   | 1      | 2         | 2      

So it's due the final line:
```csharp 
months = (days >= 30 * (factor + precision)) ? maxMonths : maxMonths - 1;
```

Changing the final line to the below fixed this issue, it returns maxMonths if it is equal to factor and it has failed the precision check (I don't know if this is the correct way to do it, I'll have a go at refactoring it and cleaning it up):
```csharp
months = (days >= 30 * (factor + precision)) ? maxMonths : (maxMonths == factor ? maxMonths : maxMonths - 1);
```

**Comment by tompazourek** [comment]
@AKTheKnight Thanks a lot for your help with this. Unfortunately, I do not have any other test cases. This was the only one that I randomly stumbled upon.

I still don't really follow what's going on there with the `factor` and `maxMonths` and how it it all supposed to work. But I'm sure if you do a PR, @onovotny will review it.

**Comment by clairernovotny** [comment]
Thank you for the original report, @tompazourek, and thank you to @AKTheKnight for the early root-cause analysis. The shared precision fix is now on main, and PR #1819 adds exact regression coverage for the 59, 60, and 61-day DateTimeOffset cases. This will be included in the next Humanizer release.
